import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { 
  ArrowLeft, CheckCircle2, Circle, Clock, 
  Target, Users, Trash2, AlertCircle, TrendingUp,
  Share2, Plus, Calendar, History, X, ChevronRight
} from 'lucide-react';
import api from '../services/api';

const EventDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [event, setEvent] = useState(null);
  const [userSalary, setUserSalary] = useState(0); 
  const [loading, setLoading] = useState(true);
  
  // States para sa Payment Modal
  const [showPayModal, setShowPayModal] = useState(false);
  const [selectedMember, setSelectedMember] = useState(null);
  const [paymentAmount, setPaymentAmount] = useState('');

  useEffect(() => {
    fetchEventDetails();
    fetchUserSalary();
  }, [id]);

  const fetchEventDetails = async () => {
    try {
      const res = await api.get(`/events/${id}`);
      setEvent(res.data);
    } catch (err) {
      console.error("Error fetching event details:", err);
      navigate('/events');
    } finally {
      setLoading(false);
    }
  };

  const fetchUserSalary = async () => {
    try {
      const res = await api.get('/auth/user'); 
      setUserSalary(res.data.monthly_salary || 0);
    } catch (err) {
      console.error("Salary sync failed");
    }
  };

  const calculateLaborHours = (amount) => {
    if (!userSalary || userSalary <= 0) return "0h";
    const hourlyRate = userSalary / 160;
    const hours = amount / hourlyRate;
    return hours.toFixed(1) + "h";
  };

  const shareToMessenger = () => {
    const totalCollected = event.members.reduce((sum, m) => sum + m.amount_paid, 0);
    const progress = Math.min((totalCollected / event.target_amount) * 100, 100).toFixed(0);
    
    const text = `📊 EXPENSEPAL LOG: ${event.title}\n` +
                 `💰 Goal: ₱${event.target_amount.toLocaleString()}\n` +
                 `📈 Total Collected: ₱${totalCollected.toLocaleString()} (${progress}%)\n\n` +
                 event.members.map(m => `${m.is_paid ? '✅' : '⏳'} ${m.name}: ₱${m.amount_paid}`).join('\n') +
                 `\n\n*Transparency record generated by ExpensePal*`;

    navigator.clipboard.writeText(text);
    alert("Full transparency log copied to clipboard!");
  };

  // BAGONG ADD: Add Contribution Logic (Parang sa Savings)
  const handleAddContribution = async (e) => {
    e.preventDefault();
    if (!paymentAmount || parseFloat(paymentAmount) <= 0) return;

    try {
      const newAmount = selectedMember.amount_paid + parseFloat(paymentAmount);
      const isNowPaid = event.type === 'fixed' 
        ? newAmount >= (event.target_amount / event.members.length)
        : newAmount >= (event.target_amount / event.members.length); // Adjustable logic

      // Ina-update natin ang member details sa database
      const res = await api.put(`/events/${id}/member/${selectedMember._id}`, {
        amount_paid: newAmount,
        is_paid: isNowPaid,
        payment_date: new Date() // I-record ang date ng transaction
      });

      setEvent(res.data);
      setShowPayModal(false);
      setPaymentAmount('');
      setSelectedMember(null);
    } catch (err) {
      alert("Payment update failed");
    }
  };

  if (loading) return <div className="p-20 text-center text-cyan-400 font-black animate-pulse uppercase tracking-[0.3em]">Syncing Transparency Logs...</div>;
  if (!event) return null;

  const totalCollected = event.members.reduce((sum, m) => sum + m.amount_paid, 0);
  const progressPercent = Math.min((totalCollected / event.target_amount) * 100, 100);
  const remainingAmount = Math.max(event.target_amount - totalCollected, 0);
  const perMemberTarget = event.target_amount / event.members.length;

  return (
    <div className="p-8 space-y-8 animate-in fade-in duration-500 text-left bg-[#001B3D] min-h-screen">
      {/* Top Nav */}
      <div className="flex justify-between items-center">
        <button onClick={() => navigate('/events')} className="flex items-center gap-2 text-gray-500 hover:text-white transition-colors font-bold uppercase text-[10px] tracking-[0.2em]">
          <ArrowLeft size={16} /> Back to Group Events
        </button>
        <button onClick={shareToMessenger} className="flex items-center gap-2 bg-indigo-500 hover:bg-indigo-600 text-white px-6 py-3 rounded-2xl font-black uppercase text-[10px] tracking-[0.2em] transition-all shadow-lg">
          <Share2 size={16} /> Share Transparency Log
        </button>
      </div>

      {/* Hero Progress Section */}
      <div className="bg-[#05192e]/60 p-10 rounded-[3rem] border border-white/5 shadow-2xl relative overflow-hidden">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center">
          <div className="space-y-4">
            <span className="px-4 py-1 rounded-full text-[10px] font-black uppercase tracking-widest border bg-cyan-400/10 text-cyan-400 border-cyan-400/20">
              {event.type === 'fixed' ? 'Fixed Bill Splitting' : 'Flexible Goal Tracker'}
            </span>
            <h1 className="text-5xl font-black text-white uppercase tracking-tighter">{event.title}</h1>
            <p className="text-gray-400 font-medium text-lg italic">Trust-based tracking for the whole team.</p>
          </div>

          <div className="bg-[#001B3D]/50 p-8 rounded-[2rem] border border-white/5 space-y-6 shadow-inner">
            <div className="flex justify-between items-end">
              <div>
                <p className="text-[10px] text-gray-500 font-black uppercase tracking-widest mb-1">Overall Collection</p>
                <p className="text-4xl font-black text-white">₱{totalCollected.toLocaleString()} <span className="text-lg text-gray-500 font-medium">/ ₱{event.target_amount.toLocaleString()}</span></p>
              </div>
              <div className="text-right">
                <p className="text-[10px] text-indigo-400 font-black uppercase tracking-widest mb-1">Labor Impact</p>
                <p className="text-2xl font-black text-indigo-400 italic">-{calculateLaborHours(remainingAmount)}</p>
              </div>
            </div>
            
            <div className="h-4 bg-navy-900 rounded-full overflow-hidden border border-white/5 shadow-inner">
              <div className="h-full bg-gradient-to-r from-cyan-500 to-indigo-500 transition-all duration-1000 shadow-[0_0_15px_rgba(34,211,238,0.3)]" style={{ width: `${progressPercent}%` }} />
            </div>
            <p className="text-center text-[10px] text-gray-500 font-black uppercase tracking-[0.4em]">
              {remainingAmount <= 0 ? "🎯 Event Fully Funded" : `₱${remainingAmount.toLocaleString()} to reach target`}
            </p>
          </div>
        </div>
      </div>

      {/* Member Management Grid */}
      <div className="space-y-6">
        <h2 className="text-xl font-black text-white uppercase tracking-widest flex items-center gap-3 ml-4">
          <Users size={24} className="text-cyan-400" /> Member Contribution Status
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {event.members.map((member) => {
            const memberProgress = Math.min((member.amount_paid / perMemberTarget) * 100, 100);
            return (
              <div 
                key={member._id}
                onClick={() => { setSelectedMember(member); setShowPayModal(true); }}
                className={`p-6 rounded-[2.5rem] border transition-all cursor-pointer group relative overflow-hidden ${
                  member.is_paid 
                  ? 'bg-emerald-500/5 border-emerald-500/20 shadow-lg shadow-emerald-500/5' 
                  : 'bg-[#05192e]/40 border-white/5 hover:border-cyan-400/30 shadow-xl'
                }`}
              >
                <div className="flex items-center gap-5 mb-4 relative z-10">
                  <img src={member.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${member.name}`} className="h-14 w-14 rounded-2xl bg-[#001B3D] border border-white/10 shadow-lg" alt="" />
                  <div className="flex-1">
                    <h3 className="font-black text-white uppercase tracking-tight text-lg">{member.name}</h3>
                    <div className="flex justify-between items-center mt-1">
                      <span className={`text-[10px] font-black uppercase ${member.is_paid ? 'text-emerald-400' : 'text-cyan-400'}`}>
                        ₱{member.amount_paid.toLocaleString()} Paid
                      </span>
                      <span className="text-[9px] text-gray-500 font-bold uppercase">Target: ₱{perMemberTarget.toLocaleString()}</span>
                    </div>
                  </div>
                  {member.is_paid ? <CheckCircle2 className="text-emerald-400" size={24} /> : <div className="w-6 h-6 rounded-full border-2 border-white/10" />}
                </div>

                {/* Individual Progress Bar */}
                <div className="h-1.5 w-full bg-black/20 rounded-full overflow-hidden mt-2 border border-white/5">
                  <div className={`h-full transition-all duration-700 ${member.is_paid ? 'bg-emerald-500' : 'bg-cyan-500'}`} style={{ width: `${memberProgress}%` }} />
                </div>
                
                <div className="mt-4 flex justify-between items-center opacity-0 group-hover:opacity-100 transition-opacity">
                  <span className="text-[9px] text-gray-500 font-black uppercase tracking-widest flex items-center gap-1"><History size={12}/> View History</span>
                  <span className="text-[9px] text-cyan-400 font-black uppercase tracking-widest flex items-center gap-1">Add Payment <ChevronRight size={12}/></span>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* PAYMENT MODAL (Katulad ng Savings Logic) */}
      {showPayModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-[#000a1a]/95 backdrop-blur-xl">
          <div className="bg-[#001B3D] border border-white/10 w-full max-w-md rounded-[3rem] p-10 shadow-3xl animate-in zoom-in duration-300">
            <div className="flex justify-between items-center mb-8">
              <div className="flex items-center gap-4">
                <img src={selectedMember?.avatar} className="w-12 h-12 rounded-xl bg-white/5" alt="" />
                <div>
                  <h2 className="text-2xl font-black text-white uppercase tracking-tighter">{selectedMember?.name}</h2>
                  <p className="text-gray-500 text-[10px] font-black uppercase tracking-[0.2em]">Update Contribution</p>
                </div>
              </div>
              <button onClick={() => setShowPayModal(false)} className="text-gray-500 hover:text-white transition-colors"><X size={24} /></button>
            </div>

            <form onSubmit={handleAddContribution} className="space-y-6">
              <div className="bg-[#05192e] p-6 rounded-2xl border border-white/5 space-y-2">
                <p className="text-[10px] font-black text-gray-500 uppercase tracking-widest">Amount to Add (₱)</p>
                <input 
                  autoFocus
                  type="number" 
                  value={paymentAmount} 
                  onChange={(e) => setPaymentAmount(e.target.value)}
                  className="w-full bg-transparent text-white text-4xl font-black outline-none placeholder:text-white/5"
                  placeholder="0.00"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="bg-white/5 p-4 rounded-2xl border border-white/5">
                  <p className="text-[9px] text-gray-500 font-black uppercase tracking-widest">Already Paid</p>
                  <p className="text-white font-black text-lg">₱{selectedMember?.amount_paid.toLocaleString()}</p>
                </div>
                <div className="bg-white/5 p-4 rounded-2xl border border-white/5">
                  <p className="text-[9px] text-gray-500 font-black uppercase tracking-widest">Goal Due</p>
                  <p className="text-white font-black text-lg">₱{perMemberTarget.toLocaleString()}</p>
                </div>
              </div>

              <button type="submit" className="w-full bg-cyan-400 hover:bg-cyan-300 text-[#001B3D] py-5 rounded-2xl font-black uppercase tracking-[0.2em] shadow-lg shadow-cyan-400/20 transition-all active:scale-95">
                Confirm Payment
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default EventDetails;